name: stream_chat_flutter
homepage: https://github.com/GetStream/stream-chat-flutter
description: Stream Chat official Flutter SDK. Build your own chat experience using Dart and Flutter.
version: 1.5.4
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  stream_chat_flutter_core: ^3.0.0
  photo_view: ^0.12.0
  rxdart: ^0.27.1
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  jiffy: ^4.1.0
  flutter_svg: ^0.22.0
  flutter_portal: ^0.4.0
  cached_network_image: ^3.1.0
  shimmer: ^2.0.0
  flutter_markdown: ^0.6.2
  url_launcher: ^6.0.9
  awesome_emojis: ^0.1.1
  video_player: ^2.1.12
  chewie: ^1.2.2
  file_picker: ^3.0.3
  image_picker: ^0.8.2
  flutter_keyboard_visibility: ^5.0.3
  video_compress: ^3.1.0
  visibility_detector: ^0.2.0
  meta: ^1.3.0
  lottie: ^1.1.0
  substring_highlight: ^1.0.33
  flutter_slidable: ^0.6.0
  image_gallery_saver: ^1.6.9
  share_plus: ^2.1.4
  photo_manager: ^1.2.8
  ezanimation: ^0.5.0
  synchronized: ^3.0.0
  characters: ^1.1.0
  dio: ^4.0.0
  path_provider: ^2.0.2
  video_thumbnail: ^0.3.3
  fluttertoast: ^8.0.7
  receive_sharing_intent: ^1.4.5
  collection: ^1.15.0-nullsafety.4



flutter:
  assets:
    - images/
    - svgs/
    - lib/svgs/
    - animations/

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.12
  pedantic: ^1.11.1